Repository may-tas/TextEditingApp, pull requests merged in 2025-08, with the labels that each got.

#57 Added Custom Snackbar
  lib/ui/screens/canvas_screen.dart
  lib/ui/widgets/background_color_tray.dart
  lib/utils/custom_snackbar.dart
Labels: level 2, gssoc25

#62 Background Color Tray issue solution 🎨
  lib/cubit/canvas_cubit.dart
  lib/cubit/canvas_state.dart
  lib/ui/screens/canvas_screen.dart
Labels: level 1, gssoc25

#70 Pull Request: Add Rich Text Copy Feature with Formatting Support
  .metadata
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  lib/cubit/canvas_cubit.dart
  lib/models/text_item_model.dart
  lib/ui/widgets/font_controls.dart
  pubspec.lock
  pubspec.yaml
Labels: level2, gssoc25

#71 UX: Improve text editing workflow with single-tap
  lib/ui/widgets/editable_text_widget.dart
Labels: level1
