Repository may-tas/TextEditingApp, pull requests merged in 2025-07, with the labels that each got.

#26 Refactor: Update color opacity to use `withAlpha`, replacing deprecated `withOpacity`. Added mounted checks between async gaps.
  lib/ui/screens/canvas_screen.dart
  lib/ui/widgets/editable_text_widget.dart
  lib/ui/widgets/font_controls.dart
Labels: level 1, gssoc25

#30 Refactor: Enhance font size adjustment with a dialog and slider for better UX
  lib/ui/widgets/font_controls.dart
Labels: enhancement, level 2, gssoc25

#36 Refactor: Improve text editing validation and structure in EditTextDialog
  lib/ui/widgets/editable_text_widget.dart
Labels: level 1, gssoc25

#42 [ENHANCEMENT] Improve Text Movement
  lib/ui/screens/canvas_screen.dart
Labels: enhancement, level 1, gssoc25

#48 Added Clear Formatting/Restore Default Button
  android/gradle/wrapper/gradle-wrapper.properties
  android/settings.gradle
  lib/ui/widgets/font_controls.dart
Labels: level 1, gssoc25
