Repository may-tas/TextEditingApp, pull requests merged in 2025-09, with the labels that each got.

#90 Added the Feature to Highlight Text #81
  lib/cubit/canvas_cubit.dart
  lib/models/text_item_model.dart
  lib/ui/widgets/editable_text_widget.dart
  lib/ui/widgets/font_controls.dart
Labels: level1, gssoc25

#92 feat: add text alignment options (left, right, center, justify)
  lib/cubit/canvas_cubit.dart
  lib/cubit/canvas_state.dart
  lib/models/text_item_model.dart
  lib/ui/widgets/editable_text_widget.dart
  lib/ui/widgets/font_controls.dart
Labels: enhancement, level1, gssoc25

#96 Updating markup file with automation
  .all-contributorsrc
  .github/workflows/contributors.yml
  README.md
  add-all-contributors.sh
  get-contributors.sh
  package-lock.json
  package.json
Labels: level2, gssoc25

#98 feat: drawing canvas with brush tool (Fixes #93)
  .gitignore
  lib/cubit/canvas_cubit.dart
  lib/cubit/canvas_state.dart
  lib/models/draw_model.dart
  lib/ui/screens/canvas_screen.dart
  lib/ui/screens/save_page_dialog.dart
  lib/ui/screens/saved_pages.dart
  lib/ui/widgets/drawing/brush_size_preview_painter.dart
  lib/ui/widgets/drawing/drawing.dart
  lib/ui/widgets/drawing/drawing_painter.dart
  lib/ui/widgets/drawing/drawing_tools_panel.dart
  lib/ui/widgets/drawing_canvas.dart
  pubspec.yaml
Labels: level3, gssoc25

#107 fix: conflicting snackbars
  lib/cubit/canvas_cubit.dart
  lib/cubit/canvas_state.dart
  lib/ui/screens/canvas_screen.dart
  lib/ui/screens/save_page_dialog.dart
  lib/ui/screens/saved_pages.dart
Labels: level2, gssoc25
